### ISSUE TITLE
Problem with unified sec groups using azurecp

### ISSUE THREAD

**Issue by schrockmatthew** [Yvand/AzureCP#143]
We use ver: AzureCP 19.0.20210211.1285 for SP 2019

recently, we have encountered an issue with the unified groups. Users who are members of these groups encounter permission denied message when going to site. Workaround is to add the directly to SP site group. I seen a similar post when users were using ver 15 but haven’t been able to track this down. This sporadic behavior as well nothing consistent. Do you have suggestions/thoughts?

**Comment by Yvand** [comment]
You need to verify a couple of things:
- Is Azure AD adding the group membership in the SAML token? If yes, what is the claim type / claim value?
- Is AzureCP configured to do augmentation?

**Comment by schrockmatthew** [comment]
Is Azure AD adding the group membership in the SAML token? If yes, what is the claim type / claim value? ​Good question...does the below help?


[cid:96fa75ce-bc6a-4280-af50-ee110d2c0238]

Is AzureCP configured to do augmentation? ​Yes

________________________________

**Comment by Yvand** [comment]
@schrockmatthew I think not all your message was posted correctly, especially the picture I think you intended to attach

**Comment by schrockmatthew** [comment]
(attached) Is this better?
________________________________

**Comment by Yvand** [comment]
You can simply navigate to the issue and see by yourself that it is not

**Comment by schrockmatthew** [comment]
Sorry to be so late but this is the exact error we're receiving:

[AzureCP] Unexpected error(s) occurred in AugmentEntity:  [EXCEPTION 1]: System.FormatException: Cannot add value because header 'Authorization' does not support multiple values.. Callstack:   
 at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)    
 at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)    
 at azurecp.AADAppOnlyAuthenticationProvider.<AuthenticateRequestAsync>d__13.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
 at Microsoft.Graph.AuthenticationHandler.<SendRetryAsync>d__15.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
 at Microsoft.Graph.AuthenticationHandler.<SendAsync>d__16.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
 at Microsoft.Graph.HttpProvider.<SendRequestAsync>d__19.MoveNext()

**Comment by schrockmatthew** [comment]
The lookup gets the following:

[AzureCP] Unexpected error occurred while getting access token for tenant 'btlaw.microsoftonline.com' on cloud instance 'AzurePublic': System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel., Callstack:   
 at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)    
 at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

**Comment by Yvand** [comment]
It looks like a TLS 1.2 is not enabled / not enabled correctly on the SharePoint servers.
Can you follow [this article](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client) to configure it?
