### ISSUE TITLE
Error when adding a tenant

### ISSUE THREAD

**Issue by benjamingournay2** [Yvand/AzureCP#9]
When i click "test tenant connection", i get the following error:

Unable to connect to Azure tenantIt may be expected if w3wp process of central admin has intentionally no access to Azure.One or more errors occurred.Error detail: Insufficient privileges to complete the operation. 

When i look at the error logs, I can see that error:
[AzureCP] Unexpected error while testing connectivity: System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request., Callstack:   
 at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)    
 at System.Data.Services.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)    
 at System.Data.Services.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)    
 at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<>c__DisplayClass4c`2.<ExecuteAsync>b__4a(IAsyncResult r)    
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location where exception was thrown ---    
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)    
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()    
 at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsync>d__4e`2.MoveNext()

What could be my issue ?

**Comment by Yvand** [comment]
The app registered on Azure probably misses permission "Read directory data".
Please follow [this link](https://yvand.github.io/AzureCP/Create-App-In-AAD.html) to register the app correctly

**Comment by benjamingournay2** [comment]
The app registered on Azure has the permission "Read directory data". 
Do you have any ideas what else it could be ?

**Comment by benjamingournay2** [comment]
Do we need to enable Microsoft Graph ? and to give permissions to that service ?

**Comment by benjamingournay2** [comment]
I granted Read directory data yesterday in application permissions and I did not grant anything in delegated permissions. This morning, I still have the issue unfortunately

**Comment by Yvand** [comment]
Just in case, can you try to register a new application, grant only "Read directory data" under "Application permissions" and test if it works?

**Comment by benjamingournay2** [comment]
We created a new app but still the same error:
![tenantcustomclaims](https://user-images.githubusercontent.com/35489873/35148102-e8cdb9dc-fd08-11e7-850f-b05b9b97e9f2.png)

**Comment by benjamingournay2** [comment]
Do you have an idea what can cause that issue when I click "test tenant connection" ?
![image](https://user-images.githubusercontent.com/35489873/35229591-119d5588-ff94-11e7-9752-67f812bb52ca.png)

**Comment by Yvand** [comment]
Can you ignore this error, add the connection and test directly the people picker?
You can monitor AzureCP activity in SharePoint logs if you filter on Product/Area "AzureCP"
If people picker doesn't work, can you try to [update AzureCP](https://yvand.github.io/AzureCP/Update-AzureCP.html) with the latest Beta, which you can [download here](https://github.com/Yvand/AzureCP/releases/tag/v10.Beta)?

**Comment by benjamingournay2** [comment]
Hi Yvan,

We have the following unexpected errors :

[AzureCP] Validation with AAD lookup created 0 permissions instead of 1 expected. Aborting operation

[AzureCP] Unexpected error while getting users in tenant hugge.onMicrosoft.com: System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request., Callstack:
 at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult)
 at System.Data.Services.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult)
 at System.Data.Services.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult)
 at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<>c__DisplayClass4c`2.<ExecuteAsync>b__4a(IAsyncResult r)
 at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsync>d__4e`2.MoveNext()

[AzureCP] ODataErrorException occurred while querying tenant 'hugge.onMicrosoft.com': Insufficient privileges to complete the operation., Callstack:    at azurecp.AzureCP.<>c__DisplayClass27_0.<<QueryAzureADAsync>b__1>d.MoveNext().


[cid:image005.jpg@01D3942A.44DD2FC0]

Azure CP is in the people picker:
[cid:image003.png@01D3942A.29CFAE10]

There is no resolution (ADFS30 is our trusted provider for ADFS):
[cid:image004.png@01D3942A.29CFAE10]
The beta 3 is installed and tenant added:
[cid:image006.png@01D3942A.44DD2FC0]


Thks for help,

Best regards,



De : Yvan Duhamel [mailto:notifications@github.com]
Envoyé : mardi, 23 janvier 2018 08:57
À : Yvand/AzureCP <AzureCP@noreply.github.com>
Cc : GOURNAY Benjamin <Benjamin.Gournay@hcuge.ch>; Author <author@noreply.github.com>
Objet : Re: [Yvand/AzureCP] Error when adding a tenant (#9)


Can you ignore this error, add the connection and test directly the people picker?
You can monitor AzureCP activity in SharePoint logs if you filter on Product/Area "AzureCP"
If people picker doesn't work, can you try to update AzureCP<https://yvand.github.io/AzureCP/Update-AzureCP.html> with the latest Beta, which you can download here<https://github.com/Yvand/AzureCP/releases/tag/v10.Beta>?

**Comment by Yvand** [comment]
Error message is "Insufficient privileges to complete the operation", which should be resolved by granting "Read directory data" only under "Application permissions" (and not to delegate permissions).
I cannot explain why you keep getting this error after setting permissions like described above...

**Comment by Markus-MEEQIT** [comment]
Make sure you have actually granted the saved permissions in Azure Portal, by clicking the Grant Permissions button in the blade prior to the Enable Access blade. The portal is a bit confusing in that it first asks you to save permissions but you then also have to grant the saved permissions.
